<?php


namespace app\store\controller;

use xsframe\base\BaseController;
use think\Controller;
use think\Request;
use think\App;

abstract class Base extends BaseController
{
    protected $pIndex;
    protected $pSize;

    protected $app;
    protected $header;
    protected $params;

    protected $siteRoot;
    protected $view;

    protected $controller;
    protected $action;
    protected $url;
    protected $iaRoot;

    protected $loginSessionKey;
    protected $isLogin;
    protected $memberId;
    protected $expire = 86400;

    public function __construct(Request $request, App $app)
    {
        parent::__construct($request, $app);

        $this->header = $this->request->header();
        $this->app    = $app;
        $this->params = $this->request->param();

        if (method_exists($this, '_home_initialize')) {
            $this->_home_initialize();
        }
    }

    // 课程不存在直接返回首页
    protected function errorUrl($msg = '', $url = '')
    {
        $this->redirect('/');
        return false;
    }

    // 初始化
    protected function _home_initialize()
    {
        $this->view   = $this->app['view'];
        $this->pIndex = $this->request->param('page') ?? 1;
        $this->pSize  = $this->request->param('size') ?? ($this->request->param('limit') ?? 16);

        $this->loginSessionKey = '__home_session';

        $this->isLogin = $this->checkUser();
        $this->checkRoute();

        $this->_init();
    }

    // 初始化
    protected function _init()
    {
    }

    // 引入模板
    protected function template($name, $var = [])
    {
        $baseVar                = [];
        $baseVar['controller']  = $this->controller;
        $baseVar['action']      = $this->action;
        $baseVar['isLogin']     = $this->isLogin;
        $baseVar['siteRoot']    = $this->siteRoot;
        $var['moduleSiteRoot']  = $this->moduleSiteRoot;
        $var['moduleAttachUrl'] = $this->moduleAttachUrl;
        $baseVar['memberInfo']  = $this->getMemberInfo();

        $baseVar['title']       = "星数为来数字化开发引擎";
        $baseVar['keywords']    = "星数为来数字化开发引擎,PHP快速开发框架,PHP微信开发框架,PHP小程序开发框架,PHP后台管理开发框架,ThinkPHP管理后台,TP多应用开发框架,Bootstrap后台,星数应用市场";
        $baseVar['description'] = "星数为来数字化开发引擎是一款基于ThinkPHP6+Bootstrap+require+js+vue+html+css的多应用综合性的软件开发引擎框架";

        $var = array_merge($baseVar, $var);
        return view($name, $var); // TODO: Change the autogenerated stub
    }

    private function checkRoute()
    {

    }

    private function getMemberInfo()
    {
        if ($this->isLogin) {
            $memberInfo = $_COOKIE['memberInfo'] ?? [];
            if (!empty($this->memberId) && empty($memberInfo)) {
                $memberInfo = db('xsd_ke_member')->field("id,username,nickname,avatar")->where(['id' => $this->memberId])->find();
                isetcookie('memberInfo', json_encode($memberInfo), 7 * $this->expire, true);
            } else {
                $memberInfo = json_decode($memberInfo, true);
            }
            $memberInfo['avatar'] = tomedia($memberInfo['avatar']);
        } else {
            $memberInfo = [];
            isetcookie("memberInfo", false, -100);
        }
        return $memberInfo;
    }

    // 校验登录
    private function checkUser()
    {
        $isLogin = true;
        if ($this->controller != 'login') {
            $homeSession = $_COOKIE[$this->loginSessionKey] ?? '';
            if (!empty($homeSession)) {
                $homeSession = json_decode(authcode($homeSession), true);
                $memberInfo  = db('xsd_ke_member')->field("id,password,salt")->where(['id' => $homeSession['mid']])->find();

                if (!(is_array($memberInfo)) || ($homeSession['hash'] != md5($memberInfo['password'] . $memberInfo['salt']))) {
                    $isLogin = false;
                }
                $this->memberId = $memberInfo['id'];
            } else {
                isetcookie($this->loginSessionKey, false, -100);
                $isLogin = false;
            }
        }
        return $isLogin;
    }
}