<?php


namespace xsframe\base;

use think\facade\Cache;
use xsframe\traits\ServiceTraits;

class BaseService extends BaseController
{
    protected $expire = 7200;

    /**
     * 引入后台通用的traits
     */
    use ServiceTraits;

    // 初始化
    protected function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }
}