<?php

// +----------------------------------------------------------------------
// | 星数 [ WE CAN DO IT JUST THINK ]
// +----------------------------------------------------------------------
// | Copyright (c) 2020~2021 http://xsframe.cn All rights reserved.
// +----------------------------------------------------------------------
// | Licensed ( http://www.apache.org/licenses/LICENSE-2.0 )
// +----------------------------------------------------------------------
// | Author: guiHai <786824455@qq.com>
// +----------------------------------------------------------------------

namespace xsframe\base;

use think\App;
use think\Request;
use think\response\Json;

abstract class WebBaseController extends BaseController
{
    protected $pIndex;
    protected $pSize;

    protected $app;
    protected $header;
    protected $params;

    protected $siteRoot;
    protected $view;

    protected $controller;
    protected $action;
    protected $url;
    protected $iaRoot;

    protected $loginSessionKey;
    protected $isLogin;
    protected $memberId;
    protected $expire = 86400;

    public function __construct(Request $request, App $app)
    {
        parent::__construct($request, $app);

        $this->header = $this->request->header();
        $this->app = $app;
        $this->params = $this->request->param();

        if (method_exists($this, '_home_initialize')) {
            $this->_home_initialize();
        }
    }

    // 初始化
    protected function _home_initialize()
    {
        $this->view = $this->app['view'];
        $this->pIndex = $this->request->param('page') ?? 1;
        $this->pSize = $this->request->param('size') ?? ($this->request->param('limit') ?? 16);

        $this->loginSessionKey = "__{$this->module}_home_session";

        $this->isLogin = $this->checkLogin();

        $this->_init();
    }

    // 初始化
    protected function _init()
    {
    }

    // 引入模板
    protected function template($name, $var = []): \think\response\View
    {
        $baseVar = [];
        $baseVar['controller'] = $this->controller;
        $baseVar['action'] = $this->action;
        $baseVar['isLogin'] = $this->isLogin;
        $baseVar['siteRoot'] = $this->siteRoot;

        $var['moduleSiteRoot'] = $this->moduleSiteRoot;
        $var['moduleAttachUrl'] = $this->moduleAttachUrl;

        $website = $this->moduleSetting['website'] ?? [];
        if (!empty($website)) {
            $website = set_medias($website, ['logo', 'favicon']);
            $baseVar['website'] = array_merge($baseVar, $website);
        }

        $var = array_merge($baseVar, $var);

        if (!('' == pathinfo($name, PATHINFO_EXTENSION))) {
            $moduleName = app('http')->getName();
            $name = APP_PATH . "/" . $moduleName . "/view/" . ltrim($name, '/');
        }

        return view($name, $var); // TODO: Change the autogenerated stub
    }

    // 校验登录
    private function checkLogin(): bool
    {
        $homeSession = $_COOKIE[$this->loginSessionKey] ?? '';
        if (!empty($homeSession)) {
            $homeSession = json_decode(authcode($homeSession), true);
            $this->memberId = $homeSession['mid'];
            $isLogin = !empty($homeSession['mid']);
        } else {
            isetcookie($this->loginSessionKey, false, -100);
            $isLogin = false;
        }
        return $isLogin;
    }
}