<?php


namespace app\admin\controller;


use think\facade\Config;
use xsframe\base\AdminBaseController;
use xsframe\wrapper\UserWrapper;

class Base extends AdminBaseController
{
    public function _admin_initialize()
    {
        parent::_admin_initialize(); // TODO: Change the autogenerated stub
        $this->checkRouter();
    }

    // 防止普通用户进入超级管理后台
    public function checkRouter()
    {
        $isAdmin = $this->module == 'admin'; // 是否超级管理后台
        $notMap = strtolower($this->controller) != 'util' && $this->action != 'map'; // 是否地图页面
        $notSetDefaultModule = strtolower($this->controller) != 'system' && $this->action != 'setAccountDefaultModule'; // 是否设置默认模块

        if ($isAdmin && $notMap && $notSetDefaultModule) {
            $adminSession = $this->adminSession;

            if (!empty($adminSession)) {

                # 非管理员用户一律不得进入平台端
                if ($adminSession['role'] != 'owner') {
                    $moduleInfo = UserWrapper::getModuleInfoByUserId($this->adminSession['uid']);
                    $uniacid = $moduleInfo['uniacid'];
                    $moduleName = $moduleInfo['module'];

                    if (!empty($moduleName)) {
                        $realUrl = UserWrapper::getModuleOneUrl($moduleName, true);
                        $url = webUrl(rtrim($realUrl, '.html'), ['i' => $uniacid]);
                        header('location: ' . $url);
                    } else {
                        header('location: ' . url('/admin/error/index', ['type' => 403]));
                    }
                    exit();
                }

            }
        }
    }
}