<?php


namespace app\admin\controller;


use think\facade\Config;
use xsframe\base\AdminBaseController;
use xsframe\wrapper\UserWrapper;

class Base extends AdminBaseController
{
    public function _admin_initialize()
    {
        parent::_admin_initialize(); // TODO: Change the autogenerated stub
        $this->checkRouter();
    }

    // 防止普通用户进入超级管理后台
    public function checkRouter()
    {
        $isAdmin = $this->module == 'admin';
        $notMap = $this->controller != 'util' && $this->action != 'map';
        $notSetDefaultModule = $this->controller != 'system' && $this->action != 'setAccountDefaultModule';

        if ($isAdmin && $notMap && $notSetDefaultModule) {
            $adminSession = $this->adminSession;

            if (!empty($adminSession)) {

                # 非管理员用户一律不得进入平台端
                if ($adminSession['role'] != 'owner') {
                    $moduleName = UserWrapper::getModuleNameByUserId($this->adminSession['uid']);

                    if (!empty($moduleName)) {
                        $url = UserWrapper::getModuleOneUrl($moduleName, true);
                        header('location: ' . $url);
                    } else {
                        header('location: ' . url('/admin/error/index', ['type' => 403]));
                    }
                    exit();
                }

            }
        }
    }
}